language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "O7x6z35g7lYram01qiX74lebi3OMmwMbLxCakiKiPKJT9uRUbkZEdWXATsi8kr7xuklZXsI6kQmJTzs+UVfrffpPTBkGQfAUpPkQCE+hX9puTcAY2KJ02g/bWRzbhhrs1LaNEkfV7ZaYS7/7HDhlzTEZPr0eQqBg8Ok9r6c++j0="
    on:
      tags: true
      all_branches: true
