language: node_js
node_js:
- '0.10'
use_sudo: false
deploy:
  provider: npm
  email: sqrt@octoblu.com
  api_key:
    secure: EY2Undbk4l38bKXG1BBcnliKAgCzuY49d1hK7dhDFLJbYHQImIikxc7L0rawQR0Z7DHQw1SEuRTuuJDg02htHlXR3gZJ2d9Xzz99f2uW9ctwYgv8mtPo2m4LWxug2fraJRacan0eE9tBoQa/rdns/MpPCfkha6Zv9lXO685R+jI=
  on:
    tags: true
    all_branches: true
